C++11 requires a space between literal and identifier
This fixes the following Clang/ GCC errors:

```
	/home/travis/build/lemenkov/sems/apps/db_reg_agent/DBRegAgent.cpp:211:25: error:
	      invalid suffix on literal; C++11 requires a space between literal and
	      identifier [-Wreserved-user-defined-literal]
	    ERROR("registering "MOD_NAME" DI interface\n");
				^
	/home/travis/build/lemenkov/sems/apps/db_reg_agent/DBRegAgent.cpp:913:18: error:
	      invalid suffix on literal; C++11 requires a space between literal and
	      identifier [-Wreserved-user-defined-literal]
	  DBG("removing "MOD_NAME" registrations from Event Dispatcher...\n");
```

Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>